### ISSUE TITLE
ros2.repo file does not provide the specific commit id, is that ok?

### ISSUE THREAD

**Issue by crazyhank** [ros2/ros2#1219]
I found that there are no commit id information in ros2.repo file if you build source from scratch, for example:
```
ros2/rmw_fastrtps:
    type: git
    url: https://github.com/ros2/rmw_fastrtps.git
    version: galactic
```
so, I get the latest branch source code each time when I build, right?
If so, the problem is if I want to build galactic from source, my build result is different from binary installation? Is that OK?
