### ISSUE TITLE
Fails to parse config with array of objects 

### ISSUE THREAD

**Issue by trydald** [ros2/ros2#1380]
## Bug report

**Required Info:**

- Operating System: 
  - Ubuntu 22.04
- Installation type: 
  - binaries
- Version or commit hash:
  - Humble
- DDS implementation:
  - ?
- Client library (if applicable):
  - rclcpp

#### Steps to reproduce issue

Launch any service with a parameter YAML-file. E.g. [cpp_pubsub](https://docs.ros.org/en/humble/Tutorials/Beginner-Client-Libraries/Writing-A-Simple-Cpp-Publisher-And-Subscriber.html)-example form ROS tutorial.  
The parameters file should contain an array of objects, where at least one of the members is a numeric value

```
ros2 launch cpp_pubsub cpp_pubsub.launch.py
```

#### config/params.yml
```
talker:
  ros__parameters:
    talkers:
      - id: 1
        name: 'talker_1'
        position: [ 1.0, 2.0 ]
      - id: 2
        name: 'talker_2'
        position: [ 1.0, 2.0 ]
```

#### launch/cpp_pubsub.launch.py
``` 
import os
from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch_ros.actions import Node

def generate_launch_description():
    return LaunchDescription([
        Node(
            package="cpp_pubsub",
            executable="talker",
            name="talker_node",
            output="screen",
            emulate_tty=True,
            parameters=[
                os.path.join(
                    get_package_share_directory('cpp_pubsub'),
                    'config', 'params.yml')
            ]
        )
    ])
```

#### Expected behavior

Should parse the array of objects that has numeric members. 

#### Actual behavior

Fails to parse file. 

``` 
[talker-1] [ERROR] [1677070766.532342488] [rcl]: Failed to parse global arguments
[talker-1] terminate called after throwing an instance of 'rclcpp::exceptions::RCLInvalidROSArgsError'
[talker-1]   what():  failed to initialize rcl: Couldn't parse params file: '--params-file /home/ros2_ws/install/cpp_pubsub/share/cpp_pubsub/config/params.yml'. Error: Sequence should be of same type. Value type 'string' do not belong at line_num 5, at ./src/parse.c:422, at ./src/rcl/arguments.c:406
[ERROR] [talker-1]: process has died [pid 683099, exit code -6, cmd '/home/ros2_ws/install/cpp_pubsub/lib/cpp_pubsub/talker --ros-args -r __node:=talker_node --params-file /home/ros2_ws/install/cpp_pubsub/share/cpp_pubsub/config/params.yml'].
``` 

#### Additional information

If the integers are quoted the YML-file is parsed.

#### config/params.yml
``` 
talker:
  ros__parameters:
    talkers:
      - id: '1'
        name: 'talker_1'
        position: [ '1.0', '2.0' ]
      - id: '2'
        name: 'talker_2'
        position: [ '1.0', '2.0' ]
```

**Comment by sloretz** [comment]
In the example it looks like "talkers" is a list of dictionaries. ROS 2 parameter lists/arrays can only be the types here: https://design.ros2.org/articles/ros_parameters.html#supported-datatypes

I think  workaround is to nest the parameters rather than using a list (I didn't try this config locally, but I think this is right).

```yaml
talker:
  ros__parameters:
    talkers:
      talker_1:
        id: '1'
        position: [ '1.0', '2.0' ]
      talker_2:
        id: '2'
        position: [ '1.0', '2.0' ]
```

A colleague of mine suggested we could make the error message more clear - saying lists of dictionaries aren't supported and recommending this style.
