### ISSUE TITLE
ros2 param dump spells out # Parameter not set

### ISSUE THREAD

**Issue by jackiescanlon** [ros2/ros2#1517]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 22.04
- Installation type:
  - Binaries
- Version or commit hash:
  - ros-iron-rclpy apt package version 4.1.4-1jammy.20231205.160931
- DDS implementation:
  - CycloneDDS
- Client library (if applicable):
  - rclcpy

#### Steps to reproduce issue
1. Create a node with this code:
```py
#!/usr/bin/env python3
import rclpy
import rclpy.node
from rcl_interfaces.msg import ParameterDescriptor, ParameterType


class ParamDemo(rclpy.node.Node):
    def __init__(self):
        super().__init__("param_demo")

        self.declare_parameter(
            "param_1",
            "param_1_default_value",
            descriptor=ParameterDescriptor(type=ParameterType.PARAMETER_STRING),
        )

        self.declare_parameter(
            "param_2",
            descriptor=ParameterDescriptor(type=ParameterType.PARAMETER_STRING),
        )


def main():
    rclpy.init()
    node = ParamDemo()
    rclpy.spin(node)


if __name__ == "__main__":
    main()
```
2. Run it:
```
ros2 run my_package parameter_node.py
```

#### Expected behavior
`ros2 param dump /param_demo` shows that `param_1` is set to `param_1_default_value` and `param_2` is unset

#### Actual behavior
`ros2 param dump` reports that `param_1` is set to `#` and `param_2` is set to ` `

#### Additional information

1. If you add several more parameters, you can see the erroneous parameter values spell out `# Parameter not set`, and any parameters that go past that character length (19) are not showed. (You can see `param_9` is omitted in the example below, even though I've declared it).
```
❯ ros2 param dump /param_demo
/param_demo:
  ros__parameters:
    param_1: '#'
    param_10: ' '
    param_11: P
    param_12: a
    param_13: r
    param_14: a
    param_15: m
    param_16: e
    param_17: t
    param_18: e
    param_19: r
    param_2: ' '
    param_20: n
    param_3: o
    param_4: t
    param_5: ' '
    param_6: s
    param_7: e
    param_8: t
```

3. Individual `ros2 param get`s seem to work fine:
```
❯ ros2 param get /param_demo param_1
String value is: param_1_default_value
❯ ros2 param get /param_demo param_2
Parameter not set
```
