### ISSUE TITLE
Error with rcutils when running colcon build

### ISSUE THREAD

**Issue by jff8** [ros2/ros2#767]
## Bug report

**Required Info:**

- Operating System:
  - Raspbian buster on RPi4
- Installation type:
  - https://index.ros.org/doc/ros2/Installation/Eloquent/Linux-Development-Setup/
- Version or commit hash:
  - Eloquent and Dashing
- DDS implementation:
  - Default
- Client library (if applicable):
  -  N/A 

#### Steps to reproduce issue
Followed steps as per <https://index.ros.org/doc/ros2/Installation/Eloquent/Linux-Development-Setup/ to build ROS2 on Raspberry Pi 4

When running:
colcon build --symlink-install

Get error with rcutils:
Failed   <<< rcutils	[ Exited with code 1 ]

```

#### Expected behavior
Expect colcon to complete with no critical errors


#### Actual behavior
Fails with this error:

CMake Error at /home/pi/install/launch_testing_ament_cmake/share/launch_testing_ament_cmake/cmake/launch_testing_ament_cmake-extras.cmake:17 (find_package):
  By not providing "Findpython_cmake_module.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "python_cmake_module", but CMake did not find one.

  Could not find a package configuration file provided by
  "python_cmake_module" with any of the following names:

    python_cmake_moduleConfig.cmake
    python_cmake_module-config.cmake

  Add the installation prefix of "python_cmake_module" to CMAKE_PREFIX_PATH
  or set "python_cmake_module_DIR" to a directory containing one of the above
  files.  If "python_cmake_module" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  /home/pi/install/launch_testing_ament_cmake/share/launch_testing_ament_cmake/cmake/launch_testing_ament_cmakeConfig.cmake:38 (include)
  /home/pi/install/ament_lint_auto/share/ament_lint_auto/cmake/ament_lint_auto_find_test_dependencies.cmake:36 (find_package)
  CMakeLists.txt:120 (ament_lint_auto_find_test_dependencies)

#### Additional information
Cmake version 3.13.4 which installs by default on Raspbian buster.
Also has the same error with DASHING


#### Implementation considerations
<!-- Relevant information on how the feature could be implemented and pros and cons of the different solutions -->

**Comment by Jesus805** [comment]
@dirk-thomas I would like to add that I'm also getting this exact issue on a RPi4 with a freshly installed Raspbian Buster.
This is the output of `colcon build --symlink-install`
```
Starting >>> shared_queues_vendor
--- stderr: rcutils
/usr/bin/ld: CMakeFiles/test_atomics_executable.dir/test/test_atomics.c.o: in fu                              nction `main':
test_atomics.c:(.text+0x11a8): undefined reference to `__atomic_store_8'
/usr/bin/ld: test_atomics.c:(.text+0x11c0): undefined reference to `__atomic_loa                              d_8'
/usr/bin/ld: test_atomics.c:(.text+0x1268): undefined reference to `__atomic_sto                              re_8'
/usr/bin/ld: test_atomics.c:(.text+0x12b8): undefined reference to `__atomic_exc                              hange_8'
/usr/bin/ld: test_atomics.c:(.text+0x12f8): undefined reference to `__atomic_loa                              d_8'
/usr/bin/ld: test_atomics.c:(.text+0x13cc): undefined reference to `__atomic_sto                              re_8'
/usr/bin/ld: test_atomics.c:(.text+0x13e8): undefined reference to `__atomic_loa                              d_8'
/usr/bin/ld: test_atomics.c:(.text+0x1484): undefined reference to `__atomic_sto                              re_8'
/usr/bin/ld: test_atomics.c:(.text+0x14c8): undefined reference to `__atomic_exc                              hange_8'
/usr/bin/ld: test_atomics.c:(.text+0x150c): undefined reference to `__atomic_loa                              d_8'
/usr/bin/ld: test_atomics.c:(.text+0x1dd8): undefined reference to `__atomic_sto                              re_8'
/usr/bin/ld: test_atomics.c:(.text+0x1df4): undefined reference to `__atomic_loa                              d_8'
/usr/bin/ld: test_atomics.c:(.text+0x1ea0): undefined reference to `__atomic_sto                              re_8'
/usr/bin/ld: test_atomics.c:(.text+0x1ef4): undefined reference to `__atomic_exc                              hange_8'
/usr/bin/ld: test_atomics.c:(.text+0x1f38): undefined reference to `__atomic_loa                              d_8'
/usr/bin/ld: test_atomics.c:(.text+0x2008): undefined reference to `__atomic_sto                              re_8'
/usr/bin/ld: test_atomics.c:(.text+0x2020): undefined reference to `__atomic_loa                              d_8'
/usr/bin/ld: test_atomics.c:(.text+0x20b8): undefined reference to `__atomic_sto                              re_8'
/usr/bin/ld: test_atomics.c:(.text+0x20f8): undefined reference to `__atomic_exc                              hange_8'
/usr/bin/ld: test_atomics.c:(.text+0x2138): undefined reference to `__atomic_loa                              d_8'
/usr/bin/ld: test_atomics.c:(.text+0x27e8): undefined reference to `__atomic_sto                              re_8'
/usr/bin/ld: test_atomics.c:(.text+0x2804): undefined reference to `__atomic_loa                              d_8'
/usr/bin/ld: test_atomics.c:(.text+0x28b0): undefined reference to `__atomic_sto                              re_8'
/usr/bin/ld: test_atomics.c:(.text+0x2904): undefined reference to `__atomic_exc                              hange_8'
/usr/bin/ld: test_atomics.c:(.text+0x2948): undefined reference to `__atomic_loa                              d_8'
/usr/bin/ld: test_atomics.c:(.text+0x2a18): undefined reference to `__atomic_sto                              re_8'
/usr/bin/ld: test_atomics.c:(.text+0x2a30): undefined reference to `__atomic_loa                              d_8'
/usr/bin/ld: test_atomics.c:(.text+0x2ac8): undefined reference to `__atomic_sto                              re_8'
/usr/bin/ld: test_atomics.c:(.text+0x2b08): undefined reference to `__atomic_exc                              hange_8'
/usr/bin/ld: test_atomics.c:(.text+0x2b48): undefined reference to `__atomic_loa                              d_8'
/usr/bin/ld: test_atomics.c:(.text+0x3278): undefined reference to `__atomic_sto                              re_8'
/usr/bin/ld: test_atomics.c:(.text+0x3294): undefined reference to `__atomic_loa                              d_8'
/usr/bin/ld: test_atomics.c:(.text+0x3340): undefined reference to `__atomic_sto                              re_8'
/usr/bin/ld: test_atomics.c:(.text+0x3394): undefined reference to `__atomic_exc                              hange_8'
/usr/bin/ld: test_atomics.c:(.text+0x33d8): undefined reference to `__atomic_loa                              d_8'
/usr/bin/ld: test_atomics.c:(.text+0x34a8): undefined reference to `__atomic_sto                              re_8'
/usr/bin/ld: test_atomics.c:(.text+0x34c0): undefined reference to `__atomic_loa                              d_8'
/usr/bin/ld: test_atomics.c:(.text+0x3558): undefined reference to `__atomic_sto                              re_8'
/usr/bin/ld: test_atomics.c:(.text+0x3598): undefined reference to `__atomic_exc                              hange_8'
/usr/bin/ld: test_atomics.c:(.text+0x35d8): undefined reference to `__atomic_loa                              d_8'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/test_atomics_executable.dir/build.make:85: test_atomics                              _executable] Error 1
make[1]: *** [CMakeFiles/Makefile2:424: CMakeFiles/test_atomics_executable.dir/a                              ll] Error 2
make: *** [Makefile:141: all] Error 2
---
Failed   <<< rcutils    [ Exited with code 2 ]
Aborted  <<< urdf
Aborted  <<< shared_queues_vendor
--- stderr: rviz_ogre_vendor
/usr/bin/ld: ../../lib/libOgreMain.so.1.12.1: undefined reference to `__atomic_fetch_add_8'
collect2: error: ld returned 1 exit status
make[5]: *** [Tools/VRMLConverter/CMakeFiles/VRMLConverter.dir/build.make:175: bin/VRMLConverter] Error 1
make[4]: *** [CMakeFiles/Makefile2:1611: Tools/VRMLConverter/CMakeFiles/VRMLConverter.dir/all] Error 2
make[4]: *** Waiting for unfinished jobs....
make[3]: *** [Makefile:152: all] Error 2
make[2]: *** [CMakeFiles/ogre-v1.12.1.dir/build.make:115: ogre-v1.12.1-prefix/src/ogre-v1.12.1-stamp/ogre-v1.12.1-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:137: CMakeFiles/ogre-v1.12.1.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
---
Aborted  <<< rviz_ogre_vendor

Summary: 84 packages finished [32min 22s]
  1 package failed: rcutils
  3 packages aborted: rviz_ogre_vendor shared_queues_vendor urdf
  3 packages had stderr output: fastrtps rcutils rviz_ogre_vendor
  210 packages not processed
```
This is my `vcs export --exact`
```
repositories:
  build/foonathan_memory_vendor/foo_mem-ext-prefix/src/foo_mem-ext:
    type: git
    url: https://github.com/foonathan/memory.git
    version: 8f6a027d473f9b4796509158962d8ddf89fbe086
  src/ament/ament_cmake:
    type: git
    url: https://github.com/ament/ament_cmake.git
    version: 0.8.2
  src/ament/ament_index:
    type: git
    url: https://github.com/ament/ament_index.git
    version: 0.7.2
  src/ament/ament_lint:
    type: git
    url: https://github.com/ament/ament_lint.git
    version: 0.8.1
  src/ament/ament_package:
    type: git
    url: https://github.com/ament/ament_package.git
    version: 0.8.7
  src/ament/googletest:
    type: git
    url: https://github.com/ament/googletest.git
    version: 2ba0f63751cd94815a9aff30f85579fedc7f0e16
  src/ament/uncrustify_vendor:
    type: git
    url: https://github.com/ament/uncrustify_vendor.git
    version: 1.3.0
  src/eProsima/Fast-CDR:
    type: git
    url: https://github.com/eProsima/Fast-CDR.git
    version: v1.0.11
  src/eProsima/Fast-RTPS:
    type: git
    url: https://github.com/eProsima/Fast-RTPS.git
    version: 16c8effab426da4ddaee2c58dbc94804a3778001
  src/eProsima/foonathan_memory_vendor:
    type: git
    url: https://github.com/eProsima/foonathan_memory_vendor.git
    version: v0.4.0
  src/eclipse-cyclonedds/cyclonedds:
    type: git
    url: https://github.com/eclipse-cyclonedds/cyclonedds.git
    version: 08d9c296f1b569c18188528fd5e8f086e94dd67d
  src/micro-ROS/ros_tracing/ros2_tracing:
    type: git
    url: https://gitlab.com/micro-ROS/ros_tracing/ros2_tracing.git
    version: 0.2.10
  src/osrf/osrf_pycommon:
    type: git
    url: https://github.com/osrf/osrf_pycommon.git
    version: 0.1.9
  src/osrf/osrf_testing_tools_cpp:
    type: git
    url: https://github.com/osrf/osrf_testing_tools_cpp.git
    version: 1.2.1
  src/ros-perception/laser_geometry:
    type: git
    url: https://github.com/ros-perception/laser_geometry.git
    version: 2.1.0
  src/ros-planning/navigation_msgs:
    type: git
    url: https://github.com/ros-planning/navigation_msgs.git
    version: 2.0.2
  src/ros-visualization/interactive_markers:
    type: git
    url: https://github.com/ros-visualization/interactive_markers.git
    version: 2.0.1
  src/ros-visualization/python_qt_binding:
    type: git
    url: https://github.com/ros-visualization/python_qt_binding.git
    version: 1.0.3
  src/ros-visualization/qt_gui_core:
    type: git
    url: https://github.com/ros-visualization/qt_gui_core.git
    version: ae49aeb235f96d8a9d759ff33c0a7c0745a252d1
  src/ros-visualization/rqt:
    type: git
    url: https://github.com/ros-visualization/rqt.git
    version: 1.0.5
  src/ros-visualization/rqt_action:
    type: git
    url: https://github.com/ros-visualization/rqt_action.git
    version: 1.0.1
  src/ros-visualization/rqt_console:
    type: git
    url: https://github.com/ros-visualization/rqt_console.git
    version: 38dfbd83d73a8f40c1f2ac09eb62e148a14f0ba9
  src/ros-visualization/rqt_graph:
    type: git
    url: https://github.com/ros-visualization/rqt_graph.git
    version: 1.0.3
  src/ros-visualization/rqt_msg:
    type: git
    url: https://github.com/ros-visualization/rqt_msg.git
    version: 1.0.2
  src/ros-visualization/rqt_plot:
    type: git
    url: https://github.com/ros-visualization/rqt_plot.git
    version: 1.0.7
  src/ros-visualization/rqt_publisher:
    type: git
    url: https://github.com/ros-visualization/rqt_publisher.git
    version: 1.0.5
  src/ros-visualization/rqt_py_console:
    type: git
    url: https://github.com/ros-visualization/rqt_py_console.git
    version: 1.0.0
  src/ros-visualization/rqt_reconfigure:
    type: git
    url: https://github.com/ros-visualization/rqt_reconfigure.git
    version: 1.0.4
  src/ros-visualization/rqt_service_caller:
    type: git
    url: https://github.com/ros-visualization/rqt_service_caller.git
    version: 1.0.3
  src/ros-visualization/rqt_shell:
    type: git
    url: https://github.com/ros-visualization/rqt_shell.git
    version: 1.0.0
  src/ros-visualization/rqt_srv:
    type: git
    url: https://github.com/ros-visualization/rqt_srv.git
    version: 1.0.1
  src/ros-visualization/rqt_top:
    type: git
    url: https://github.com/ros-visualization/rqt_top.git
    version: 1.0.0
  src/ros-visualization/rqt_topic:
    type: git
    url: https://github.com/ros-visualization/rqt_topic.git
    version: 1.1.0
  src/ros/class_loader:
    type: git
    url: https://github.com/ros/class_loader.git
    version: 1.4.0
  src/ros/pluginlib:
    type: git
    url: https://github.com/ros/pluginlib.git
    version: 2.4.1
  src/ros/resource_retriever:
    type: git
    url: https://github.com/ros/resource_retriever.git
    version: 2.2.1
  src/ros/robot_state_publisher:
    type: git
    url: https://github.com/ros/robot_state_publisher.git
    version: 2.3.1
  src/ros/ros_environment:
    type: git
    url: https://github.com/ros/ros_environment.git
    version: 2.4.1
  src/ros/ros_tutorials:
    type: git
    url: https://github.com/ros/ros_tutorials.git
    version: 3485a9fbd2aa59b1a4e4ca9b6a96535af6eedb4c
  src/ros/urdfdom_headers:
    type: git
    url: https://github.com/ros/urdfdom_headers.git
    version: 1.0.4
  src/ros2/ament_cmake_ros:
    type: git
    url: https://github.com/ros2/ament_cmake_ros.git
    version: 0.8.0
  src/ros2/common_interfaces:
    type: git
    url: https://github.com/ros2/common_interfaces.git
    version: 0.8.1
  src/ros2/console_bridge_vendor:
    type: git
    url: https://github.com/ros2/console_bridge_vendor.git
    version: 1.2.0
  src/ros2/demos:
    type: git
    url: https://github.com/ros2/demos.git
    version: 0.8.4
  src/ros2/eigen3_cmake_module:
    type: git
    url: https://github.com/ros2/eigen3_cmake_module.git
    version: 0.1.1
  src/ros2/example_interfaces:
    type: git
    url: https://github.com/ros2/example_interfaces.git
    version: 0.7.1
  src/ros2/examples:
    type: git
    url: https://github.com/ros2/examples.git
    version: 0.8.2
  src/ros2/geometry2:
    type: git
    url: https://github.com/ros2/geometry2.git
    version: 3a088b144de003747479f53546203b1a24a6687e
  src/ros2/kdl_parser:
    type: git
    url: https://github.com/ros2/kdl_parser.git
    version: 2.2.0
  src/ros2/launch:
    type: git
    url: https://github.com/ros2/launch.git
    version: 0.9.5
  src/ros2/launch_ros:
    type: git
    url: https://github.com/ros2/launch_ros.git
    version: 0.9.4
  src/ros2/libyaml_vendor:
    type: git
    url: https://github.com/ros2/libyaml_vendor.git
    version: 1.0.0
  src/ros2/message_filters:
    type: git
    url: https://github.com/ros2/message_filters.git
    version: 3.2.3
  src/ros2/orocos_kinematics_dynamics:
    type: git
    url: https://github.com/ros2/orocos_kinematics_dynamics.git
    version: 3.2.1
  src/ros2/poco_vendor:
    type: git
    url: https://github.com/ros2/poco_vendor.git
    version: 1.2.0
  src/ros2/python_cmake_module:
    type: git
    url: https://github.com/ros2/python_cmake_module.git
    version: 0.8.0
  src/ros2/rcl:
    type: git
    url: https://github.com/ros2/rcl.git
    version: 1b00d8bb6e54b8a4a9657286151602cae933625a
  src/ros2/rcl_interfaces:
    type: git
    url: https://github.com/ros2/rcl_interfaces.git
    version: 0.8.0
  src/ros2/rcl_logging:
    type: git
    url: https://github.com/ros2/rcl_logging.git
    version: 0.3.3
  src/ros2/rclcpp:
    type: git
    url: https://github.com/ros2/rclcpp.git
    version: 0.8.3
  src/ros2/rclpy:
    type: git
    url: https://github.com/ros2/rclpy.git
    version: 6d592210008cd5bf0600d33d662138cdc4ed78a0
  src/ros2/rcpputils:
    type: git
    url: https://github.com/ros2/rcpputils.git
    version: 0.2.1
  src/ros2/rcutils:
    type: git
    url: https://github.com/ros2/rcutils.git
    version: 0.8.4
  src/ros2/realtime_support:
    type: git
    url: https://github.com/ros2/realtime_support.git
    version: 0.8.2
  src/ros2/rmw:
    type: git
    url: https://github.com/ros2/rmw.git
    version: 0.8.1
  src/ros2/rmw_connext:
    type: git
    url: https://github.com/ros2/rmw_connext.git
    version: 0.8.1
  src/ros2/rmw_cyclonedds:
    type: git
    url: https://github.com/ros2/rmw_cyclonedds.git
    version: 0.4.4
  src/ros2/rmw_fastrtps:
    type: git
    url: https://github.com/ros2/rmw_fastrtps.git
    version: 0.8.1
  src/ros2/rmw_implementation:
    type: git
    url: https://github.com/ros2/rmw_implementation.git
    version: 0.8.2
  src/ros2/rmw_opensplice:
    type: git
    url: https://github.com/ros2/rmw_opensplice.git
    version: 0.8.1
  src/ros2/ros1_bridge:
    type: git
    url: https://github.com/ros2/ros1_bridge.git
    version: 0.8.1
  src/ros2/ros2cli:
    type: git
    url: https://github.com/ros2/ros2cli.git
    version: 38a5552b0d8c5eb1cfd35829a0b14a0f41f135cb
  src/ros2/ros_testing:
    type: git
    url: https://github.com/ros2/ros_testing.git
    version: 0.2.0
  src/ros2/rosbag2:
    type: git
    url: https://github.com/ros2/rosbag2.git
    version: 0.2.4
  src/ros2/rosidl:
    type: git
    url: https://github.com/ros2/rosidl.git
    version: 0.8.1
  src/ros2/rosidl_dds:
    type: git
    url: https://github.com/ros2/rosidl_dds.git
    version: 0.7.1
  src/ros2/rosidl_defaults:
    type: git
    url: https://github.com/ros2/rosidl_defaults.git
    version: 0.8.0
  src/ros2/rosidl_python:
    type: git
    url: https://github.com/ros2/rosidl_python.git
    version: 0.8.1
  src/ros2/rosidl_runtime_py:
    type: git
    url: https://github.com/ros2/rosidl_runtime_py.git
    version: 0.8.2
  src/ros2/rosidl_typesupport:
    type: git
    url: https://github.com/ros2/rosidl_typesupport.git
    version: 0.8.0
  src/ros2/rosidl_typesupport_connext:
    type: git
    url: https://github.com/ros2/rosidl_typesupport_connext.git
    version: 0.8.4
  src/ros2/rosidl_typesupport_fastrtps:
    type: git
    url: https://github.com/ros2/rosidl_typesupport_fastrtps.git
    version: 0.8.0
  src/ros2/rosidl_typesupport_opensplice:
    type: git
    url: https://github.com/ros2/rosidl_typesupport_opensplice.git
    version: 0.8.1
  src/ros2/rviz:
    type: git
    url: https://github.com/ros2/rviz.git
    version: 7.0.3
  src/ros2/spdlog_vendor:
    type: git
    url: https://github.com/ros2/spdlog_vendor.git
    version: 1.0.1
  src/ros2/sros2:
    type: git
    url: https://github.com/ros2/sros2.git
    version: 0.8.1
  src/ros2/system_tests:
    type: git
    url: https://github.com/ros2/system_tests.git
    version: 0.8.0
  src/ros2/test_interface_files:
    type: git
    url: https://github.com/ros2/test_interface_files.git
    version: 0.8.0
  src/ros2/tinydir_vendor:
    type: git
    url: https://github.com/ros2/tinydir_vendor.git
    version: 1.1.1
  src/ros2/tinyxml2_vendor:
    type: git
    url: https://github.com/ros2/tinyxml2_vendor.git
    version: 0.6.1
  src/ros2/tinyxml_vendor:
    type: git
    url: https://github.com/ros2/tinyxml_vendor.git
    version: 0.7.0
  src/ros2/tlsf:
    type: git
    url: https://github.com/ros2/tlsf.git
    version: 0.5.0
  src/ros2/unique_identifier_msgs:
    type: git
    url: https://github.com/ros2/unique_identifier_msgs.git
    version: 2.1.0
  src/ros2/urdf:
    type: git
    url: https://github.com/ros2/urdf.git
    version: 2.2.0
  src/ros2/urdfdom:
    type: git
    url: https://github.com/ros2/urdfdom.git
    version: 2.2.0
  src/ros2/yaml_cpp_vendor:
    type: git
    url: https://github.com/ros2/yaml_cpp_vendor.git
    version: 54feb9dfcf88c6925ee16aed4d5d7eda1eea946c
```
